svxlink:
  container_name: svxlink
  image: svxlink
  volumes:
    - ${PWD}/configs/svxlink.conf:/etc/svxlink/svxlink.conf
    - ${PWD}/state:/state
    - ${PWD}/ptt:/ptt
  command: svxlink
  privileged: true
  ports:
    - 5200:5200
    - 5198:5198/udp
    - 5199:5199/udp

remote1:
  container_name: remote1
  image: svxlink
  volumes:
    - ${PWD}/configs/remote1.conf:/etc/svxlink/remotetrx.conf
  command: remotetrx
  privileged: true
  ports:
    - 5211:5210

remote2:
  container_name: remote2
  image: svxlink
  volumes:
    - ${PWD}/configs/remote2.conf:/etc/svxlink/remotetrx.conf
  command: remotetrx
  privileged: true
  ports:
    - 5212:5210
