name: Test

on: workflow_dispatch
  
jobs:
  docker:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build docker image
      run: ./build-image.sh
      
    - name: Start containers
      run: docker-compose up -d

    - name: Run tests
      run: echo none yet

    - name: Stop containers
      if: always()
      run: docker-compose down
