name: Test

on:
  push:
    paths:
      - '*.py'
      - 'configs/**'
      - 'docker*'
      - 'Dockerfile'
      - 'pytest.ini'
      - 'requirements.txt'
      - 'scripts/**'
      - 'tests/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        branch:
          - master
          - hobbyscoop
          - old
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}

    - name: Build docker image
      run: scripts/build-images.sh ${{ matrix.branch }}

    - name: Create IO
      run: scripts/create-IO.sh

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        ret=0
        BRANCH=${{ matrix.branch }} pytest --html=report-${{ matrix.branch }}.html --self-contained-html || ret=1
        set -x
        git config --global user.name "GitHub Actions"
        git config --global user.email "hobbyscoop@users.noreply.github.com"
        git pull
        git add report-${{ matrix.branch }}.html
        git commit -m 'update report-${{ matrix.branch }}.html'
        git push
        exit $ret
