name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: branch to test (master is upstream, hobbyscoop is with patches)
        options:
          - master
          - hobbyscoop
        default: hobbyscoop
run-name: Test ${{ inputs.branch }}
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build docker image
      run: scripts/build-image.sh ${{ inputs.branch }}

    - name: Create IO
      run: scripts/create-IO.sh

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

