name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        branch: ["master", "hobbyscoop"]
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build docker image
      run: scripts/build-images.sh ${{ matrix.branch }}

    - name: Create IO
      run: scripts/create-IO.sh

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: BRANCH=${{ matrix.branch }} pytest || cat log && exit 1 # on error, show log and break

